### ISSUE TITLE
Regenerate SRI on build

### ISSUE THREAD

**Issue by matt-in-a-hat** [Firesphere/silverstripe-csp-headers#19]
We have JS assets which change during development, but it seems the only way to get the SRI to update is to hit `?updatesri=true` after deployment (e.g. to production). Could there be an easy way of configuring this to regenerate these when a dev/build is called?

Also, probably a separate issue, the `?updatesri=true` only works if you've got a security group with the code "administrators", so it was silently not doing anything for me because we'd changed the groups. There's probably a more reliable way of checking for an appropriate permission, and possibly could be worth throwing an error if you pass that param but don't have permission?

**Comment by Firesphere** [comment]
Very valid point. Apologies for the delayed response. This may need a build task, shouldn't be too much trouble.

You're free to open a PR yourself, but I'll have a look when I have time :)

**Comment by Firesphere** [comment]
Hey @matt-in-a-hat ,

I've had a look at this, but rebuilding the SRI during a dev/build or a flush, is not really feasible, because it would require to scan each page for separate requirements (which is a very valid thing that may happen), and especially on larger websites, this would slow down the build immensely.

I believe the best approach, is to have a build task that can be enabled manually, which will clear out all SRI records.
This way, when a page is visited, and the SRI doesn't exist yet, it will be generated on the fly.

However, SRI is primarily for _external_ scripts. Internal scripts should not need an SRI per se. This is a slightly different issue which I need to fix with some configuration settings too.

>  the ?updatesri=true only works if you've got a security group with the code "administrators", so it was silently not doing anything for me because we'd changed the groups.

This is a very out-of-the-ordinary change, which I'd rather leave up to a dev to change something if needed be. My best suggestion would be to add `?isDev=true` to your query parameters, to temporarily set your site to dev mode, bypassing the need for the `updatesri` parameter.
