### ISSUE TITLE
CSP header doesn't appear until a dev/build is run in browser

### ISSUE THREAD

**Issue by elliot-sawyer** [Firesphere/silverstripe-csp-headers#35]
We have this module installed on production servers, and discovered the header is only generated and served in the response after a dev/build is run in the browser. We normally run dev/build via the CLI.

The issue seems to be here, with `DatabaseAdmin::lastBuilt()` not recognising the database has already been built on CLI. Removing this call from the condition resolves the issue

**Comment by phptek** [comment]
I've come across this exact issue and it's because when you're running `dev/build` via the CLI, a new user-dir under `silverstripe-cache` is created: `root` so the `database-last-generated-foo` file that is expected by `DatabaseAdmin::lastBuilt()` is generated there, and not in `www-data` which is consulted when going TTW.

Running `dev/build` in the browser (which I haven't done for 10 years) "fixes" this.

**Comment by tim-mediasuite** [comment]
Added a PR that uses the same approach vendor/silverstripe/cms/code/Controllers/RootURLController.php does to redirect to dev/build if the DB isn't setup, rather than the file lastBuilt checks for.

**Comment by Firesphere** [comment]
I've added some comments on #42 , I had to restart the change, as it would be faster than a whole rebase...

And I'm now confused as to what's happening...

**Comment by Firesphere** [comment]
I think this should be resolved right now, by re-adding the changes done by @tim-mediasuite and @matt-in-a-hat and re-fixing the tests.

New release made, which hopefully resolves your problems.

Caveat, as I haven't checked, Paragon's CSP builder module, which is a dependency, has a bug which I was/am waiting for the next release to fix.
If you run in to this bug (specifically, the report URL is escaped), try using Paragon's master/main instead of a tagged release.
